package olilay.com.golemreader.parser

const val GOLEM_URL = "https://www.golem.de"
const val GOLEM_ARTICLE_CLASS = "media__teaser media__teaser--articles hentry"
const val GOLEM_MAIN_CLASS = "leader"
const val GOLEM_ARTICLE_PRE_HEADING_CLASS = "media__kicker"
const val GOLEM_ARTICLE_HEADING_CLASS = "media__headline-text"
const val GOLEM_MAIN_PRE_HEADING_CLASS = "head-meta"
const val GOLEM_MAIN_HEADING_CLASS = "head-main"
const val GOLEM_ARTICLE_LINK_CLASS = "media__link"
const val GOLEM_ARTICLE_LINK_REL = "bookmark"
const val GOLEM_ARTICLE_IMAGE_CLASS = "photo"
const val GOLEM_ARTICLE_IMAGE_CLASS_ALT = "golem-data-afterload photo"
const val GOLEM_ARTICLE_DESCRIPTION_CLASS = "media__excerpt entry-content"
const val GOLEM_ARTICLE_COMMENT_COUNT_CLASS = "icon comment-count"
const val GOLEM_ARTICLE_DATE = "authors__pubdate"
const val GOLEM_ARTICLE_AUTHOR = "authors__name"